export interface Member {
  id: string;
  email: string;
  name: string;
}

export interface Trip {
  id: string;
  title: string;
  destination: string;
  startDate: string;
  endDate: string;
  members: Member[];
}
/**
 * Represents the raw, structured JSON itinerary response generated by the Gemini model.
 * Match this against the schema your frontend card components parse.
 */
export interface GeminiItineraryPayload {
  destination: string;
  days: number;
  budget: number;
  travelStyle: string;
  overview?: string;
  schedule?: Array<{
    day: number;
    title: string;
    activities: Array<{
      time: string;
      activity: string;
      location?: string;
      estimatedCost?: string | number;
    }>;
  }>;
  packingList?: string[];
  tips?: string[];
}

/**
 * Represents a single normalized trip entity as returned by the global Redis cache database layer.
 */
export interface TripItem {
  id: string;               // The Redis key pattern string (e.g., "itinerary:Japan:7:Adventure")
  destination: string;      // Extracted parameter key
  days: number;             // Total duration parameter key
  budget: number;           // Total budget allocation parameter key
  travelStyle: string;      // Behavioral parameter key
  createdAt?: string;       // Optional string timestamp metadata
  fullData: {
    source: "redis" | "api" | string;
    data: GeminiItineraryPayload; // The pure internal travel payload block
  };
}

/**
 * Diagnostic tracking metrics used within the telemetry overview systems.
 */
export interface SystemTelemetryMetric {
  title: string;
  value: string | number;
  description: string;
  icon: string; // Used if mapping icon lookups by string key
  color: string;
  bg: string;
}

/**
 * Runtime log entry formats for developer workspace console outputs.
 */
export interface TerminalLogStream {
  id: string;
  timestamp: string;
  type: "info" | "warn" | "error" | "cache" | "system";
  message: string;
}